apiVersion: v1
kind: Service
metadata:
  name: webapp-Service
  labels:
    type: webapp
spec:
  selectors:
    matchLabels:
      type: webapp
  type: NodePort
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
      ports:
        - port: 80
          targetPort: 80
          nodePort: 30001
  

